services:
  python-app:
    build: .
    ports:
      - "8080:8080"  # If your Python script exposes a web service, adjust ports accordingly
    volumes:
      - .:/usr/src/app
    command: python ./app.py
